name: Awesome Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  awesome-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sindresorhus/awesome-lint@v0.20.0
